sudo: required
services:
- docker
language: c
compiler: gcc
os:
- linux
script:
- "./docker-build.sh"
env:
  global:
  - secure: FpI62YvrAupqNEOwlf5z3s6+4yQQKAbQ+eLpJkxIsWRGt7HlO1OXpfHat04+bPe4sied0VkYqG3ZnpspTh+YqsmITzaTGfdCcGToY807SxTqDyN+MFcyRVPqc02xYmqclTuUbtlQZSgVftlmm6qwpdkAd83Lztd8SHXo+qeZfXjVdaZxbHTpXwgBMbuZ+qRN31XUcaF9zG1Y4fpVxwmOTme0AxRnzUbNPptc/S0Fbt6R+5vhEDFaSOmYr4INfZwtBbbE5u2eTc12NpTRrsWqWv2ss1YOrIT02/oMIPfX8BVoyf62rgGco1cPabMqV/KyFKtL42atKdEVQJavTyBIP0EoOGO3qKvHrstNFBnsGgH5MIC466ROigvZW+nOCKE7rVMS3KTegwrKuHA+uA8hjp2Mpa1Cz9gjoFYK6Fl3qgLv5382NwKpK1lpTue5XyFAUfdIkEjc2TbczeIqsCgdWsEGd3MZBjMq1iPT+/hW2luHRA4vYqbuXO4FuA8eU0KODs3RRlWWFbBYEEj4mOePwq9tIHnvjhlyx/yLQQMT6EQmIk67Iu5QtfYCY3u3mE0xQ/tfCVOlb5SbLX6fjq3zQYthMPMogWxNNnaniXzg7UTsApNEYE+n0kEhvP55DKFqTliSIR19pfvb9TzBl4covkqM7Yqz+M4i/FFMsNFeKRY=
  - secure: m+dFI8aUzc01El+WldlJUNZBSE/lUpwS/kFsxQz7XAOyX/PG3jRWMIqX7yV0WEaE9irz99MkYBbffyrRRGSJa/+MpquZTDzWZWv3YMffazMBu9AN6UbgyOFbRAZ89DPA9ca2YkoZABk1S1RahyNkn377N/FfY1GkrwTc+M4qMDiHfmstHrIEaANOYcAsepu5DBnUik7ES2aVyvfwc2iYwydueO79Fb7edD3K3vW3MXSXtZKB00tZRWC2m86Cy3xngS2dYogd9BppyHpbo3MKr28i0RCk5mGnm1yodOjV/mV3sYHY9l4NcBSU8t68mcS/jLpQJvtOcCDuvIE7FhcwY+7BwS9nlRi/6en87zrC3fiovQyepEJ4fBB05sfwPvmc2ITx8A2Id7Yg97U9Aul4JHTC0oUqCZtHelwhXOhDKyactLQ4FCYEabS+8qLKabs3OFMMPm4Th9LbzhnFwxyWMCPG9BdoTFvxQBc6uIuTwPgk5o+E4jodW+CIDOmGM1A/WhyFBsKQFtOcwrbDHUvCPIbLbELhNlPwIFSTz4+A6/+FQ0ZfBDL86YRLxBIlZOdQmB3j/h/VZh6H4658lmi9Y2Y61HyWWKC8jXCixbriEN/+i4DScbJ9NjOiOBXsZsNvmZGBN1K7KYboKryccyvRLlwAMQRw69TwT99Cjk1RSCU=
deploy:
  provider: s3
  access_key_id: AKIA4H2GJQ3VFB2AJHVP
  secret_access_key:
    secure: WdWcJCMWvHH30CAG+wRvxKj1xwqx/4VHE+vOaz2wqXvhHLyZQLIUJoUOCxCTDoiQTHTqF1stJTim2j2r6FDhD9OWP2W1RpHq59JVqGID3NAL+id03jU/RlDlewWwLpmNVnbuyk2lWfIVFMWoov/+jZiAzETyV5B3gPPIhoJU+aITylX4CS9h9JQtGsOetKf9KULxC5m1s5tVgiRjVs6lAWSg+RxDFS1BkHSHvRb3WHMrcMHnO8JMGaiistxp59VHBPeSHoXqksiHxLJFNoKN6/BkHMj/AJpot79tDykUnSTQJzUeU4gOWs6bDK9nK3A6Uy3jN84RPP02hSyWE5uC7GHPqm4zf9dHFqyLSwpHUWjoKqm5HWceeKCpOnro6v6aPSZLTDcOhXI6Aaxcc1ngAF043PmNs6vXFf975l/xIU1uPTRfRINpO9d9Avlk/tVWT6B1aSKReY6wpIAK8dotg9jf8QA0d9NTRO7aplfZoPLZ9A3HMa8er7NhrGpl2I7ZpfqKjBqiHltw1xcoqD5fy/timOeJo/pLboDAmASHxcQtkl9GFaVGfR+czK74IC6TaWKW/FEvTWj7HIQ+64sDODmr/U0xvPbrIycCuuYIo6BCiwAfz6tIR6CCukHja/2QAebHiWxBBfjKITPsI4nBV3ImRYTMKuHxs+k2d4dO2aY=
  bucket: passwd-pot
  acl: public_read
  on:
    repo: dougEfresh/sshd-passwd-pot
  region: eu-central-1
  skip_cleanup: true  
  local_dir: contrib/passwd-pot/rpmbuild/RPMS/x86_64 
