sudo: required
services:
  - docker
install: make get-deps
language: c
compiler: gcc
os:
- linux
script:
- ./docker-build.sh
env:
  global:
  - secure: YLJ3/tMBolbN4c4x89xKkf/WK+CFmbSXpRahINYzh4DX1x5s66scrI2K0hgJHnfy/W9unFdOswfNA78Sk/baSmiLubRCKdXZUQlQrapOiMQcgXcnOZtk7vPH80goK6TNYN76zilLvySGsxbXbcPhf3548u+NNIlfMy5b2Ws+sMyvZu8mMkOIhwDuBlc87cPiFTRPc/nsfn81UDf6n8LvVMtC00P594ERuLbJP6rPNcUe+HZdrkz+VRHNCAdWGWZ721331njnCpcgQK47ScnCPJMCg53iyMB9ZkC2ogJwKyRs/a+Jj/jup9h6QGyHjl65IZPH8smX7u1qEDAjsLW/SzLwR0yfWOarWhGRxtqGLHn1Ylg6Jze0bi9oRYwHttityenOz0uMAcPAgDq6sn3/hU06N4Xj1kusyAkMvo4UklZwo4UvD4prmpX88XWnuE4XQL6dxw+cZ//eWDvTpyx8X8LjcQ8DUxaejeN6+hD+Vk9RW8gN0JT523FBAMTo3EqRI8XI6qwvOPm1mvVl6f80qiX5H61c+gO3wHG8N0D5mpe3tlOxkillQsHjH2guKSokzB4chDqZ/CyRrtmG1bjUeR7fqbJtbCPNwRbLcE9uhyWraj1Dd+8cTQ2gxfSNK0musF5YpXbyQ17QL7OsWKLtpKuIfuYCGDdSu5v6QvsbCgc=
  - secure: YdDa06qHZqFYOMb88F/Q11F23rmsm06Aw9LmFmeo/2NE1u2LFfNuk4ExeNxujjfRmEzt93zMlrGH04wlgGVUM1uLSw7gB+nDu0JIzBU09k7PJYZbQjZTRfmzrvrxMGsYcpYmZbXeQN5Yb+4k91yaIEHORDccF951zRI7ZZbSnYfrwyxH+wo8BQCQ8EfpBw9Nr0FBWTWLN2ch7cWB6Gxt8Liqe4hpFBRfZryJJEUgv1D2zE6++WYnttQXw8pcwd3kczVNaW7hZDZeaOfuPuR64P+yL/5oCQDvGcZW4WadbZgH8LWCnVM78AaH4WqnqSALl9GZoZxPJx07GmNwZHSihSXwEIffSH2oiznuKXBgIV275s+C6L2KPeKXK6pAgxWTwKQS4JIoUyLr/xUQuHEn1sAOCJhaZpzWnBZNnxMvhr1/qmL+KlHuiSThvurAyhTpBI0dR10M7tGgMwUTE6o9P/wRoi108MSvU6gcBKyoSHDhnCrKQCw3PkBcS/+ViuqeF7Kk7cp7QOmbf40rjbIyzKD6V8SX+/XUbglTBMa/1x5NtCtbnsM+W8mYGwbneBu4ZXSn+sc9t/bQcLEn3p/UOD4uUU7eVdoG7aXR51gBhTMH6lofJRQKz76V5aOpRZCTD2aKZXJUtrxawahTVLkycrGh3jtCKO3e/lylC/HlsDc=
  - secure: qa0Lq8UFTSmN4Ywg3cw/mUtj+gbezrYEnDAOiTUF+ks0aloFsPMlZm6t9fjZkNMW53dvCAxiopsEojOupHuzWBbvTJvQUgo7DVQLOlXhwV5kKErbtiGICiptSPuvZYXUL2pmMernx4rPVSCVYVfYJpDqZfK3OyDV+Eb/nYiN16TLo+f6AZ/6yVGLePfKi3Qs9TqnFVXPkga8lo4O0LvDtKLUoNM3SRpoUCTqwSir0m1dQ2sRroMFXE9ilaKZOR7kSgG8wmi9xZUvQM2FtRjLty8ZiqiseqC+WjT/BhlI3x8LEGl8c7ONEpW1HnATq3C6ui8KtcQAx9n/kkJQIaqPiOutYSdPqNwTg/41PdVfVERGhJ0tfS44ihvcnu98cJUZu9rF0iALi5VQf/6myJ5GUU7CDtj2hgCTNcWSm5wiOI4vo0IBMP4n7FGw999Cv6gD6OVQ4N06vNOHbioZ8aqQDF72fsnZh4v14izmG6Xlx6KgG5VveuV2giKmqjjQdaqf/ImVjb9ypI5MVx8hXIAOnKaJ2uKfsVuUuLIo+IKu0oTl88e4FmbSU81NnbbwuRKD3uC2bF3HJsAB48z4+0QL2Z8kncyF3H2qmHf6Aytc1eMCRYesKMAiug/Fb2kbNV+T2Wb59ryBWNDc0c67fep6tk6OHQNHzra/qyBjdyrDEEc=
  - COMMIT=${TRAVIS_COMMIT}

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=dougefresh/sshd-passwd-pot
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$COMMIT
  - docker push $REPO
